/**
 * Recurring task rules (T-0110): turning a rule's wall-clock schedule into the
 * next task to create.
 *
 * All arithmetic here is *local* calendar time — "every weekday at 09:00" means
 * the machine's 09:00, and a rule's day boundaries are local midnights. That is
 * why this lives in the frontend rather than next to the vault-tidy scheduler in
 * Rust: the backend has no time zone.
 *
 * Two invariants keep the rules from producing duplicates:
 *
 * - only the *latest* missed occurrence is ever returned, so an app that was
 *   closed for a week creates one task, not seven;
 * - an occurrence is consumed by recording it in `last_generated`, whether the
 *   task was created or deliberately skipped.
 */

import type { CreateTaskInput, RecurringRule, Task, TaskAssignee, TaskPriority, TaskStatus } from "@/types";

const DAY_MS = 86_400_000;

/** Nested-tag prefix marking a task as generated by a rule. */
export const RULE_TAG_PREFIX = "recurring/";

/** The marker tag every task generated by `ruleId` carries. */
export function ruleTag(ruleId: string): string {
  return `${RULE_TAG_PREFIX}${ruleId}`;
}

/** Local calendar day as an integer index (DST-safe: dates, not durations). */
function dayIndex(d: Date): number {
  return Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / DAY_MS);
}

/** Local midnight of a day index. */
function dateFromDayIndex(index: number): Date {
  const utc = new Date(index * DAY_MS);
  return new Date(utc.getUTCFullYear(), utc.getUTCMonth(), utc.getUTCDate());
}

/** `YYYY-MM-DD` -> day index; null for empty or malformed input. */
function dayIndexFromISO(iso: string): number | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso.trim());
  if (!m) return null;
  const [, y, mo, d] = m;
  return dayIndex(new Date(Number(y), Number(mo) - 1, Number(d)));
}

/** Local `YYYY-MM-DD` of a date. */
export function toISODate(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/** "HH:MM" -> minutes since local midnight; falls back to 09:00 when unusable. */
function timeMinutes(time: string): number {
  const m = /^(\d{1,2}):(\d{2})$/.exec(time.trim());
  if (!m) return 9 * 60;
  const h = Math.min(23, Number(m[1]));
  const min = Math.min(59, Number(m[2]));
  return h * 60 + min;
}

/** The rule's fire moment on a given day. */
function occurrenceAt(dayIdx: number, time: string): Date {
  const date = dateFromDayIndex(dayIdx);
  date.setMinutes(timeMinutes(time));
  return date;
}

function daysInMonth(year: number, monthIndex: number): number {
  return new Date(year, monthIndex + 1, 0).getDate();
}

/** Day index of the monthly fire day in the month containing `dayIdx`. */
function monthlyDayInMonthOf(dayIdx: number, dayOfMonth: number): number {
  const d = dateFromDayIndex(dayIdx);
  const clamped = Math.min(
    Math.max(1, dayOfMonth || 1),
    daysInMonth(d.getFullYear(), d.getMonth()),
  );
  return dayIndex(new Date(d.getFullYear(), d.getMonth(), clamped));
}

/** Day index of the monthly fire day `offset` months away from `dayIdx`. */
function monthlyDayShifted(dayIdx: number, dayOfMonth: number, offset: number): number {
  const d = dateFromDayIndex(dayIdx);
  const shifted = new Date(d.getFullYear(), d.getMonth() + offset, 1);
  return monthlyDayInMonthOf(dayIndex(shifted), dayOfMonth);
}

/** Lower bound (`start_date`) as a day index; -Infinity when unset. */
function startDay(rule: RecurringRule): number {
  const parsed = dayIndexFromISO(rule.schedule.start_date ?? "");
  return parsed ?? Number.NEGATIVE_INFINITY;
}

/**
 * The latest day the rule fires on, at or before `refDay`, ignoring the
 * `start_date` bound (applied by the callers). Null when the kind can never
 * fire (e.g. a weekly rule with no weekdays selected).
 */
function fireDayOnOrBefore(rule: RecurringRule, refDay: number): number | null {
  const s = rule.schedule;
  switch (s.kind) {
    case "weekly": {
      const days = new Set((s.weekdays ?? []).map((n) => ((n % 7) + 7) % 7));
      if (days.size === 0) return null;
      for (let back = 0; back < 7; back++) {
        const day = refDay - back;
        if (days.has(dateFromDayIndex(day).getDay())) return day;
      }
      return null;
    }
    case "monthly": {
      const inMonth = monthlyDayInMonthOf(refDay, s.day_of_month);
      return inMonth <= refDay ? inMonth : monthlyDayShifted(refDay, s.day_of_month, -1);
    }
    default: {
      // daily: every `interval_days` counted from `start_date` (or, with no
      // start date, from the epoch — every day for the interval-1 default).
      const interval = Math.max(1, s.interval_days || 1);
      const anchor = dayIndexFromISO(s.start_date ?? "") ?? 0;
      if (refDay < anchor) return null;
      const steps = Math.floor((refDay - anchor) / interval);
      return anchor + steps * interval;
    }
  }
}

/** The earliest day the rule fires on, at or after `refDay`. */
function fireDayOnOrAfter(rule: RecurringRule, refDay: number): number | null {
  const s = rule.schedule;
  switch (s.kind) {
    case "weekly": {
      const days = new Set((s.weekdays ?? []).map((n) => ((n % 7) + 7) % 7));
      if (days.size === 0) return null;
      for (let ahead = 0; ahead < 7; ahead++) {
        const day = refDay + ahead;
        if (days.has(dateFromDayIndex(day).getDay())) return day;
      }
      return null;
    }
    case "monthly": {
      const inMonth = monthlyDayInMonthOf(refDay, s.day_of_month);
      return inMonth >= refDay ? inMonth : monthlyDayShifted(refDay, s.day_of_month, 1);
    }
    default: {
      const interval = Math.max(1, s.interval_days || 1);
      const anchor = dayIndexFromISO(s.start_date ?? "") ?? 0;
      if (refDay <= anchor) return anchor;
      const steps = Math.ceil((refDay - anchor) / interval);
      return anchor + steps * interval;
    }
  }
}

/**
 * The most recent occurrence at or before `now`, or null if the rule has not
 * reached its first one yet. Only the latest is returned — missed occurrences
 * from a closed app are deliberately not backfilled.
 */
export function lastOccurrence(rule: RecurringRule, now: Date): Date | null {
  const minutes = now.getHours() * 60 + now.getMinutes();
  // Today only counts once its fire time has passed.
  const refDay = dayIndex(now) - (minutes < timeMinutes(rule.schedule.time) ? 1 : 0);
  const day = fireDayOnOrBefore(rule, refDay);
  if (day === null || day < startDay(rule)) return null;
  return occurrenceAt(day, rule.schedule.time);
}

/** The next occurrence strictly after `now` — what the settings UI previews. */
export function nextOccurrence(rule: RecurringRule, now: Date): Date | null {
  const minutes = now.getHours() * 60 + now.getMinutes();
  // Today still counts while its fire time is ahead of us.
  const refDay = dayIndex(now) + (minutes < timeMinutes(rule.schedule.time) ? 0 : 1);
  const bounded = Math.max(refDay, startDay(rule) === Number.NEGATIVE_INFINITY ? refDay : startDay(rule));
  const day = fireDayOnOrAfter(rule, bounded);
  if (day === null) return null;
  return occurrenceAt(day, rule.schedule.time);
}

/**
 * The occurrence this rule owes us, or null when it is up to date (or
 * disabled). "Owes" means: its latest occurrence has passed and has not been
 * recorded in `last_generated` yet.
 */
export function dueOccurrence(rule: RecurringRule, now: Date): Date | null {
  if (!rule.enabled) return null;
  const occurrence = lastOccurrence(rule, now);
  if (!occurrence) return null;
  const last = rule.last_generated;
  if (last != null && last * 1000 >= occurrence.getTime()) return null;
  return occurrence;
}

/** Whether a task generated by this rule is still open (not done, not archived). */
export function hasOpenTaskForRule(rule: RecurringRule, tasks: Task[]): boolean {
  const tag = ruleTag(rule.id);
  return tasks.some((t) => !t.archived && t.status !== "done" && t.tags.includes(tag));
}

/** The task a rule stamps out for one occurrence. */
export function taskInputFromRule(rule: RecurringRule, occurrence: Date): CreateTaskInput {
  const tags = [ruleTag(rule.id), ...rule.tags.filter((t) => t.trim() !== "")];
  const due =
    rule.due_offset_days == null
      ? ""
      : toISODate(dateFromDayIndex(dayIndex(occurrence) + rule.due_offset_days));
  return {
    title: rule.title.trim() || rule.id,
    status: (rule.status || "todo") as TaskStatus,
    assignee: (rule.assignee || "me") as TaskAssignee,
    project: rule.project,
    priority: (rule.priority || "medium") as TaskPriority,
    model: rule.model,
    confirm: rule.confirm,
    worktree: rule.worktree,
    due,
    tags,
    body: rule.body.trim() ? rule.body : undefined,
  };
}

/** Next free rule id (`R-001`, `R-002`, ...); ids are never reused. */
export function nextRuleId(rules: RecurringRule[]): string {
  const max = rules.reduce((acc, r) => {
    const n = Number(r.id.replace(/^R-/, ""));
    return Number.isFinite(n) ? Math.max(acc, n) : acc;
  }, 0);
  return `R-${String(max + 1).padStart(3, "0")}`;
}

/** A blank rule for the "add" button, starting today. */
export function newRule(rules: RecurringRule[]): RecurringRule {
  return {
    id: nextRuleId(rules),
    enabled: true,
    title: "",
    body: "",
    status: "todo",
    assignee: "me",
    project: "",
    priority: "medium",
    model: "",
    tags: [],
    confirm: false,
    worktree: false,
    due_offset_days: null,
    skip_if_open: true,
    schedule: {
      kind: "daily",
      interval_days: 1,
      weekdays: [1],
      day_of_month: 1,
      time: "09:00",
      start_date: toISODate(new Date()),
    },
    last_generated: null,
  };
}

/** Human-readable one-liner for a rule's schedule, e.g. "Mon, Thu at 09:00". */
export function describeSchedule(rule: RecurringRule): string {
  const s = rule.schedule;
  const names = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  switch (s.kind) {
    case "weekly": {
      const days = [...new Set((s.weekdays ?? []).map((n) => ((n % 7) + 7) % 7))].sort();
      const label = days.length ? days.map((d) => names[d]).join(", ") : "no day selected";
      return `Weekly · ${label} at ${s.time}`;
    }
    case "monthly":
      return `Monthly · day ${s.day_of_month} at ${s.time}`;
    default: {
      const n = Math.max(1, s.interval_days || 1);
      return n === 1 ? `Daily at ${s.time}` : `Every ${n} days at ${s.time}`;
    }
  }
}
